# Generated by Django 3.2.7 on 2021-09-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_log',
            name='datetime',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
